CREATE OR REPLACE PROCEDURE GET_JOIN_ACCOUNTS(S OUT SYS_REFCURSOR) AS
BEGIN
    OPEN S FOR
        SELECT a_join_id, a_account_id FROM JOIN_ACCOUNTS;
END;
/

DECLARE
    S SYS_REFCURSOR;
    A_JOIN JOIN_ACCOUNTS.a_join_id%TYPE;
    A_ACCOUNT JOIN_ACCOUNTS.a_account_id%TYPE;
BEGIN
    GET_JOIN_ACCOUNTS(S);
    LOOP
        FETCH S INTO A_JOIN, A_ACCOUNT;
        EXIT WHEN S%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(A_JOIN || ' ' || A_ACCOUNT);
    END LOOP;
    CLOSE S;
END;
/